### ISSUE TITLE
No module named 'eventrolebacklinks'

### ISSUE THREAD

**Issue by sam-m888** [uli22/MY-gramps-addons#1]
Hi Uli,

How and where is this addon meant to be used?

I attempted to add it to the Event catalog lists sidebar and get the following errors

> 2019-09-25 11:53:08.951: WARNING: _manager.py: line 308: Plugin error (from 'eventrolebacklinks'): No module named 'eventrolebacklinks'
> 2019-09-25 11:53:08.951: WARNING: grampletpane.py: line 181: Error loading gramplet 'EventRole Backlinks': skipping content
>

**Comment by uli22** [comment]
Hi Sam, 
I corrected the error regarding Capital letters in the filename.
In my version gramps 5.1.1. on Windows 10 it is working now.

**Comment by uli22** [comment]
despite of my changes this error remains.
Workaround: remove the gramplet once and add it again.

**Comment by sam-m888** [comment]
Thanks for the updated instruction on the readme.

> despite of my changes this error remains.

Ok, the work around allows me to see the gramplet in action 👍 

New Field on Gramplet

![uli22 gramplet](https://user-images.githubusercontent.com/8924713/65824971-7798bd00-e2b4-11e9-98f8-3ed2a425e5ac.png)


Original "References" Gramplet for comparison:

![orginal references](https://user-images.githubusercontent.com/8924713/65824970-7798bd00-e2b4-11e9-9a2f-26ac8c044fc4.png)

I suggest you post a message on Gramps developers mailing list asking for help with the error as a normal user will not attempt to add & remove the gramplet to get it working.

**Comment by uli22** [comment]
Code now works correctly

**Comment by sam-m888** [comment]
Will you be submitting adding it to https://github.com/gramps-project/addons-source as Pull request?

**Comment by uli22** [comment]
Hi Sam
I made a pull request and hope it will be ok. as it is the first time I do
that.
This ist the link:
https://github.com/gramps-project/addons-source/pull/243#issue-327532870

cheers
Uli

Am So., 13. Okt. 2019 um 08:33 Uhr schrieb Sam Manzi <
notifications@github.com>:
